### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by themightyoarfish** [BobMcFry/whentotalk#3]
Tried this with Chrome on Android 6. Setting Location and times dies not do anything.

**Comment by BobMcFry** [comment]
So you set at least two locations and then the sliders did not even change color (red or green)? Or did you maybe set the ranges to the full extend of 24h? Because this is a known issue where the algorithm does not work.

**Comment by themightyoarfish** [comment]
Ok yea, I did drag the sliders to the very end.

**Comment by BobMcFry** [comment]
Ok I will add this problem to the official issues, since it is not very user friendly and confusing.
